Stellar integration
EjaraApp/trustdart pull request #35
Opened 2022-09-29 09:58 UTC by Rakeally

2022-09-30 07:42 UTC, jayluxferro commented
Hi @Rakeally , I think there's no need for `createAssetAccount` since all accounts (including issuer) can be created with the `generateAddress`.

`ChangeTrust` should be renamed `CreateAsset`.

`sendAsset` should be renamed `SendAsset`.

2022-10-17 13:30 UTC, baahkusi commented
We should expose these three operations and the commands should be named as such.

- ChangeTrust
- CreateAccount
- Payment 

for payment operation it should cover for all assets including the native asset so we don't have two separate commands.

2022-10-17 13:40 UTC, baahkusi requested changes

2022-10-17 13:40 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XLM.kt
> +            "CreateAsset" -> {
change name to `ChangeTrust`

2022-10-17 13:40 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XLM.kt
> +            "SendAsset" -> {
change name to `Payment`

2022-10-17 13:40 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XLM.kt
> +            "XLM" -> {
merge this one with the above

2022-11-01 11:27 UTC, baahkusi approved these changes

2022-11-01 11:27 UTC, merged