added FA2 and FA12 to Trustdart
EjaraApp/trustdart pull request #45
Opened 2023-05-08 13:37 UTC by Rakeally

2023-05-08 14:08 UTC, jayluxferro approved these changes

2023-05-08 14:08 UTC, jayluxferro commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    .setFee((txData["fee"] as Int).toLong())
You can do this straight away.

```
txData["fee"]!!.toLong()
```

2023-05-08 14:08 UTC, jayluxferro commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    .setFee((txData["fee"] as Int).toLong())
`txData["fee"]!!.toLong()`

2023-05-08 14:08 UTC, jayluxferro commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    .setCounter((txData["counter"] as Int).toLong())
`txData["counter"]!!.toLong()`

2023-05-08 14:08 UTC, jayluxferro commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    .setGasLimit((txData["gasLimit"] as Int).toLong())
txData["gasLimit"]!!.toLong()

2023-05-08 14:08 UTC, jayluxferro commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    .setStorageLimit((txData["storageLimit"] as Int).toLong())
txData["storageLimit"]!!.toLong()

2023-05-08 14:11 UTC, jayluxferro requested changes
@Rakeally , you can cast direct too long. This helps prevent issues we had earlier with some of the tokens.

Example:

```
txData["counter"]!!.toLong()
```

2023-05-08 23:07 UTC, baahkusi requested changes
This PR seems to ignore native tezos transactions.

2023-05-08 23:12 UTC, baahkusi requested changes
It also doesn't take into account the case where user needs to do reveal

2023-05-09 15:06 UTC, baahkusi requested changes
It seems it's always doing a reveal. Reveal should only be done when specified.

2023-05-10 08:43 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/coins/XTZ.kt
> +                    operationList.operationsList.add(reveal)
fee, counter, gasLimit and storageLimit are different for reveal so have their versions.

2023-05-10 08:43 UTC, baahkusi commented on ios/Classes/coins/XTZ.swift
> +
fee, counter, gasLimit and storageLimit are different for reveal so have their versions.

2023-05-12 08:38 UTC, merged