Polygon integration
EjaraApp/trustdart pull request #50
Opened 2023-06-20 18:03 UTC by Rakeally

2023-06-21 08:37 UTC, baahkusi requested changes

2023-06-21 08:37 UTC, baahkusi commented on ios/Classes/WalletHandler.swift
> +        "BSC"   : ETH(),
Let's remove this then and just always use ETH . So all ETH compatible will just use the ETH

2023-06-21 08:37 UTC, baahkusi commented on ios/Classes/WalletHandler.swift
> +        "MATIC" : ETH()
Let's remove this then and just always use ETH . So all ETH compatible will just use the ETH

2023-06-21 08:37 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/WalletHandler.kt
> +            "BSC"   to ETH(),
Let's remove this then and just always use ETH . So all ETH compatible will just use the ETH

2023-06-21 08:37 UTC, baahkusi commented on android/src/main/kotlin/africa/ejara/trustdart/WalletHandler.kt
> +            "MATIC" to ETH(),
Let's remove this then and just always use ETH . So all ETH compatible will just use the ETH

2023-06-21 22:01 UTC, jayluxferro approved these changes

2023-06-23 09:52 UTC, baahkusi approved these changes

2023-06-23 09:52 UTC, merged